version: '3.8'
services:
  vector:
    image: "timberio/vector:0.34.1-alpine"
    container_name: vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - ./logs:/logs
    ports:
      - "4317:4317"
      - "10514:10514"
      - "1514:1514"
      - "9001:9001"
      - "8125:8125/udp"
    environment:
      DD_API_KEY: ${DD_API_KEY:-DD_API_KEY_PLACEHOLDER}
      SPLUNK_TOKEN: ${SPLUNK_TOKEN:-SPLUNK_TOKEN_PLACEHOLDER}

  op-worker-1:
    image: datadog/observability-pipelines-worker:latest
    volumes:
      - ./opw1-config.yaml:/etc/observability-pipelines-worker/config.yaml:ro
    ports:
      - "8080:8080"
    environment:
      DD_OP_WORKER_TOKEN: ${DD_OP_WORKER_TOKEN:-TOKEN_PLACEHOLDER}

  op-worker-2:
    image: datadog/observability-pipelines-worker:latest
    volumes:
      - ./opw2-config.yaml:/etc/observability-pipelines-worker/config.yaml:ro
    ports:
      - "8081:8081"
    environment:
      DD_OP_WORKER_TOKEN: ${DD_OP_WORKER_TOKEN:-TOKEN_PLACEHOLDER}

  datadog-agent:
    image: datadog/agent:latest
    environment:
      DD_API_KEY: ${DD_API_KEY:-DD_API_KEY_PLACEHOLDER}
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_DD_URL: "http://vector:9001"
      DD_LOGS_CONFIG_LOGS_DD_URL: "http://vector:9001"
    depends_on:
      - vector

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    command: ["--strict.perms=false", "-e"]
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
    depends_on:
      - vector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - ./logs:/logs:ro
    depends_on:
      - vector

  logger:
    image: busybox
    volumes:
      - ./logs:/logs
    command: sh -c 'while true; do echo "$(date) sample log" >> /logs/sample.log; sleep 1; done'
