# Observability Pipeline worker 1 configuration
# Replace placeholders with actual pipeline definition
sources:
  http_ingest:
    type: http
    address: 0.0.0.0:8080
sinks:
  discard:
    type: blackhole
